### ISSUE TITLE
Need change view button

### ISSUE THREAD

**Issue by rohmanhm** [Meadowcottage/playcode-desktop#4]
I think it will be nice if you have buttons to change the view like Codepen does. 👍🏼
So, for user that have a small monitor, it help them to keep get experience work with multi files in their workspace.

![image](https://cloud.githubusercontent.com/assets/7524911/24327109/986a87ba-11f2-11e7-92b0-fc2e26aecc4f.png)

**Comment by Meadowcottage** [comment]
This is a feature that should be passed onto the official @playcode team to help with.
I simply offer a desktop client that is a wrapper of the website 😛

**Comment by rohmanhm** [comment]
oh yeah, I forgot it.

Moved to https://github.com/playcode/playcode/issues/11
