### ISSUE TITLE
windows?

### ISSUE THREAD

**Issue by Suburbanno** [Meadowcottage/playcode-desktop#5]

**Comment by Meadowcottage** [comment]
A windows version is currently in the works don't worry.
Just working on a few fixes for it 😄

**Comment by jasondavis** [comment]
I been wanting to build a desktop app for a code playground type app for a while so this is even better than what I was thinking of!  I just need a Windows version!

**Comment by Meadowcottage** [comment]
I know the importance of a Windows version don't worry. Been busy with other projects lately. But should have the next version out soon. WITH a Windows release 😉 😄

**Comment by guzgarcia** [comment]
@Meadowcottage for Linux too?

**Comment by Meadowcottage** [comment]
I can easily create a dist for it. But no current way of testing the functionality for it 😕.
But I will see what I can do 😄

**Comment by jasondavis** [comment]
@Meadowcottage I can help test on Windows if needed

**Comment by airtonix** [comment]
@Meadowcottage It's incredibly easy to test linux support.

firstly, do not create distribution specific releases. just create an appimage. use electron-forge it makes it easy.

secondly, testing in linux or windows is easy, just fire up a virtual machine. run a live iso, don't bother creating a virtual hd.
